import streamlit as st
import google.generativeai as genai

# 1. Page Configuration
st.set_page_config(page_title="y1", layout="centered")

# Custom CSS for RTL support (Keeping it as you requested)
st.markdown("""
    <style>
    .stMarkdown { text-align: right; }
    </style>
    """, unsafe_allow_html=True)

st.title("y1")

# 2. API Key Configuration
if "GOOGLE_API_KEY" in st.secrets:
    genai.configure(api_key=st.secrets["GOOGLE_API_KEY"])
else:
    st.error("Configuration Error: GOOGLE_API_KEY not found.")
    st.stop()

# 3. Dynamic Model Selection (Updated for 2026 Multimodal Support)
@st.cache_resource
def get_model(mode="text"):
    available_models = [m.name for m in genai.list_models()]
    
    # Logic to find the best model for image generation or text
    if mode == "image":
        # Searching for Nano Banana or Gemini 3 Image capabilities
        for m in available_models:
            if 'image' in m or 'nano' in m:
                return genai.GenerativeModel(m)
    
    # Defaulting to the latest Flash or Pro for general tasks
    for m in available_models:
        if 'flash' in m or 'pro' in m:
            return genai.GenerativeModel(m)
            
    return genai.GenerativeModel('gemini-pro')

# 4. Session State for Chat History
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display Message History
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if message["type"] == "text":
            st.markdown(message["content"])
        elif message["type"] == "image":
            st.image(message["content"], caption="Generated by y1")

# 5. Chat Logic
if prompt := st.chat_input("Enter your message..."):
    # Add user message to history
    st.session_state.messages.append({"role": "user", "content": prompt, "type": "text"})
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        try:
            # Agentic Decision: Should I draw or talk?
            image_keywords = ['draw', 'generate image', 'create picture', 'paint', 'show me']
            is_image_request = any(keyword in prompt.lower() for keyword in image_keywords)

            if is_image_request:
                with st.spinner("Generating your image..."):
                    img_model = get_model(mode="image")
                    # In 2026, generate_content handles image creation if the model supports it
                    response = img_model.generate_content(prompt)
                    
                    # Check if response contains image data
                    if response.generated_images:
                        generated_img = response.generated_images[0]
                        st.image(generated_img)
                        st.session_state.messages.append({"role": "assistant", "content": generated_img, "type": "image"})
                    else:
                        st.write("I understood you want an image, but this model version didn't return one. Here is a text response instead:")
                        st.write(response.text)
            else:
                # Standard Text Response
                text_model = get_model(mode="text")
                response = text_model.generate_content(prompt)
                output = response.text
                st.markdown(output)
                st.session_state.messages.append({"role": "assistant", "content": output, "type": "text"})
                
        except Exception as e:
            st.error(f"An error occurred: {str(e)}")
